#cloud-config
users:
  - name: devops
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_KEY_CONTENT}
mounts:
  - ["/dev/disk/by-id/scsi-0HC_Volume_${VOLUME_ID}", "/home/devops/apps"]
package_update: true
package_upgrade: true
packages:
  - fail2ban
  - ufw
  - podman
runcmd:
  - systemctl enable ssh
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - ufw allow 'OpenSSH'
  - ufw allow http
  - ufw allow https
  - ufw enable
  - sed -ie '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -ie '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -ie '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding yes/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers devops' /etc/ssh/sshd_config
  - systemctl restart ssh
  - sudo systemctl enable --now cni-dhcp.socket
  - mkdir /home/devops/apps
# - mkfs.xfs /dev/disk/by-id/scsi-0HC_Volume_${VOLUME_ID}
# - echo "/dev/disk/by-id/scsi-0HC_Volume_${VOLUME_ID} /home/devops/apps xfs defaults 0 0" >> /etc/fstab
  - mount /dev/disk/by-id/scsi-0HC_Volume_${VOLUME_ID} /home/devops/apps
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - chown devops:devops /home/devops
  - chown devops:devops /home/devops/apps
  - reboot
